use pest::Parser;
use pest_derive::Parser;
use pest::iterators::Pair;

use crate::ast::*;

#[derive(Parser)]
#[grammar = "grammar.pest"]
pub struct MPCParser;

pub use pest::iterators::Pairs;
// Rule is automatically generated by pest_derive

pub fn parse_program(source: &str) -> Result<Pairs<Rule>, pest::error::Error<Rule>> {
    MPCParser::parse(Rule::program, source)
}

pub fn build_ast(pairs: Pairs<Rule>) -> Result<Program, String> {
    let mut items = Vec::new();
    
    for pair in pairs {
        match pair.as_rule() {
            Rule::program => {
                for inner_pair in pair.into_inner() {
                    match inner_pair.as_rule() {
                        Rule::item => {
                            items.push(parse_item(inner_pair)?);
                        }
                        Rule::EOI => {}
                        _ => {}
                    }
                }
            }
            _ => return Err(format!("Unexpected rule at top level: {:?}", pair.as_rule())),
        }
    }
    
    Ok(Program { items })
}

fn parse_item(pair: Pair<Rule>) -> Result<Item, String> {
    let inner_pair = pair.into_inner().next().ok_or("Empty item")?;
    
    match inner_pair.as_rule() {
        Rule::struct_def => Ok(Item::StructDef(parse_struct_def(inner_pair)?)),
        Rule::function_def => Ok(Item::FunctionDef(parse_function_def(inner_pair)?)),
        _ => Err(format!("Unexpected item rule: {:?}", inner_pair.as_rule())),
    }
}

fn parse_struct_def(pair: Pair<Rule>) -> Result<StructDef, String> {
    let mut inner = pair.into_inner();
    let name = parse_identifier(inner.next().ok_or("Missing struct name")?)?;
    
    let mut fields = Vec::new();
    for field_pair in inner {
        match field_pair.as_rule() {
            Rule::struct_field => {
                fields.push(parse_struct_field(field_pair)?);
            }
            _ => {}
        }
    }
    
    Ok(StructDef { name, fields })
}

fn parse_struct_field(pair: Pair<Rule>) -> Result<StructField, String> {
    let mut inner = pair.into_inner();
    let ty = parse_type_expr(inner.next().ok_or("Missing type in struct field")?)?;
    let name = parse_identifier(inner.next().ok_or("Missing field name")?)?;
    
    Ok(StructField { ty, name })
}

fn parse_function_def(pair: Pair<Rule>) -> Result<FunctionDef, String> {
    let mut inner = pair.into_inner();
    let name = parse_identifier(inner.next().ok_or("Missing function name")?)?;
    
    // Parse parameters (optional param_list)
    // The grammar is: "fn" ~ identifier ~ "(" ~ param_list? ~ ")" ~ "->" ~ type_expr ~ block
    // Pest gives us: identifier, param_list? (if present), type_expr, block
    let mut params = Vec::new();
    
    // Check if the next item is a param_list or type_expr
    if let Some(next_pair) = inner.next() {
        match next_pair.as_rule() {
            Rule::param_list => {
                // We have parameters
                for param_pair in next_pair.into_inner() {
                    if param_pair.as_rule() == Rule::param {
                        params.push(parse_param(param_pair)?);
                    }
                }
                // Now get the return type
            }
            Rule::type_expr => {
                // No parameters, this is the return type
                let return_type = parse_type_expr(next_pair)?;
                let body = parse_block(inner.next().ok_or("Missing function body")?)?;
                return Ok(FunctionDef {
                    name,
                    params,
                    return_type,
                    body,
                });
            }
            _ => {
                return Err(format!("Unexpected rule in function definition: {:?}", next_pair.as_rule()));
            }
        }
    }
    
    // Parse return type
    let return_type = parse_type_expr(inner.next().ok_or("Missing return type")?)?;
    
    // Parse body block
    let body = parse_block(inner.next().ok_or("Missing function body")?)?;
    
    Ok(FunctionDef {
        name,
        params,
        return_type,
        body,
    })
}

fn parse_param(pair: Pair<Rule>) -> Result<Param, String> {
    let mut inner = pair.into_inner();
    let visibility = parse_visibility(inner.next().ok_or("Missing visibility in param")?)?;
    let ty = parse_type_expr(inner.next().ok_or("Missing type in param")?)?;
    let name = parse_identifier(inner.next().ok_or("Missing param name")?)?;
    
    Ok(Param {
        visibility,
        ty,
        name,
    })
}

fn parse_type_expr(pair: Pair<Rule>) -> Result<TypeExpr, String> {
    let inner_pair = pair.into_inner().next().ok_or("Empty type expression")?;
    
    match inner_pair.as_rule() {
        Rule::array_type => Ok(TypeExpr::Array(parse_array_type(inner_pair)?)),
        Rule::base_type => Ok(TypeExpr::Base(parse_base_type(inner_pair)?)),
        Rule::struct_type => Ok(TypeExpr::Struct(parse_struct_type(inner_pair)?)),
        _ => Err(format!("Unexpected type expression rule: {:?}", inner_pair.as_rule())),
    }
}

fn parse_base_type(pair: Pair<Rule>) -> Result<BaseType, String> {
    let inner_pair = pair.into_inner().next().ok_or("Empty base type")?;
    
    match inner_pair.as_rule() {
        Rule::field_type => Ok(BaseType::Field(parse_field_type(inner_pair)?)),
        Rule::bool_type => Ok(BaseType::Bool),
        _ => Err(format!("Unexpected base type rule: {:?}", inner_pair.as_rule())),
    }
}

fn parse_field_type(pair: Pair<Rule>) -> Result<FieldType, String> {
    let mut inner = pair.into_inner();
    // Skip "Field" and "<"
    let size_str = inner
        .find(|p| p.as_rule() == Rule::integer)
        .ok_or("Missing size in Field type")?
        .as_str();
    let size = size_str.parse().map_err(|_| "Invalid integer in Field type")?;
    
    Ok(FieldType { size })
}

fn parse_array_type(pair: Pair<Rule>) -> Result<ArrayType, String> {
    let mut inner = pair.into_inner();
    // Skip "Array" and "<"
    let element_type = parse_type_expr(inner.next().ok_or("Missing element type in Array")?)?;
    // Skip ","
    let size_str = inner
        .find(|p| p.as_rule() == Rule::integer)
        .ok_or("Missing size in Array type")?
        .as_str();
    let size = size_str.parse().map_err(|_| "Invalid integer in Array type")?;
    
    Ok(ArrayType {
        element_type: Box::new(element_type),
        size,
    })
}

fn parse_struct_type(pair: Pair<Rule>) -> Result<StructType, String> {
    let name = parse_identifier(pair.into_inner().next().ok_or("Missing struct type name")?)?;
    Ok(StructType { name })
}

fn parse_visibility(pair: Pair<Rule>) -> Result<Visibility, String> {
    match pair.as_str() {
        "Public" => Ok(Visibility::Public),
        "Secret" => Ok(Visibility::Secret),
        _ => Err(format!("Invalid visibility: {}", pair.as_str())),
    }
}

fn parse_block(pair: Pair<Rule>) -> Result<Block, String> {
    let mut statements = Vec::new();
    
    for stmt_pair in pair.into_inner() {
        match stmt_pair.as_rule() {
            Rule::statement => {
                statements.push(parse_statement(stmt_pair)?);
            }
            _ => {}
        }
    }
    
    Ok(Block { statements })
}

fn parse_statement(pair: Pair<Rule>) -> Result<Statement, String> {
    let inner_pair = pair.into_inner().next().ok_or("Empty statement")?;
    
    match inner_pair.as_rule() {
        Rule::variable_decl => Ok(Statement::VariableDecl(parse_variable_decl(inner_pair)?)),
        Rule::assignment => Ok(Statement::Assignment(parse_assignment(inner_pair)?)),
        Rule::if_statement => Ok(Statement::If(parse_if_statement(inner_pair)?)),
        Rule::for_loop => Ok(Statement::ForLoop(parse_for_loop(inner_pair)?)),
        Rule::return_statement => Ok(Statement::Return(parse_return_statement(inner_pair)?)),
        Rule::directive => Ok(Statement::Directive(parse_directive(inner_pair)?)),
        Rule::expr_statement => Ok(Statement::Expr(parse_expression(inner_pair.into_inner().next().ok_or("Empty expression statement")?)?)),
        _ => Err(format!("Unexpected statement rule: {:?}", inner_pair.as_rule())),
    }
}

fn parse_variable_decl(pair: Pair<Rule>) -> Result<VariableDecl, String> {
    let mut inner = pair.into_inner();
    // Skip "let"
    let visibility = parse_visibility(inner.next().ok_or("Missing visibility in variable decl")?)?;
    let ty = parse_type_expr(inner.next().ok_or("Missing type in variable decl")?)?;
    let name = parse_identifier(inner.next().ok_or("Missing variable name")?)?;
    
    let initializer = if let Some(expr_pair) = inner.next() {
        Some(parse_expression(expr_pair)?)
    } else {
        None
    };
    
    Ok(VariableDecl {
        visibility,
        ty,
        name,
        initializer,
    })
}

fn parse_assignment(pair: Pair<Rule>) -> Result<Assignment, String> {
    let mut inner = pair.into_inner();
    let lvalue = parse_lvalue(inner.next().ok_or("Missing lvalue in assignment")?)?;
    let value = parse_expression(inner.next().ok_or("Missing value in assignment")?)?;
    
    Ok(Assignment { lvalue, value })
}

fn parse_lvalue(pair: Pair<Rule>) -> Result<LValue, String> {
    let mut inner = pair.into_inner();
    let base = parse_identifier(inner.next().ok_or("Missing base identifier in lvalue")?)?;
    
    let mut accesses = Vec::new();
    for access_pair in inner {
        match access_pair.as_rule() {
            Rule::array_access => {
                let expr = parse_expression(access_pair.into_inner().next().ok_or("Missing expression in array access")?)?;
                accesses.push(LValueAccess::Array(expr));
            }
            Rule::field_access => {
                let field_name = parse_identifier(access_pair.into_inner().next().ok_or("Missing field name")?)?;
                accesses.push(LValueAccess::Field(field_name));
            }
            _ => {}
        }
    }
    
    Ok(LValue { base, accesses })
}

fn parse_if_statement(pair: Pair<Rule>) -> Result<IfStatement, String> {
    let mut inner = pair.into_inner();
    // Skip "if"
    let condition = parse_expression(inner.next().ok_or("Missing condition in if statement")?)?;
    let then_block = parse_block(inner.next().ok_or("Missing then block in if statement")?)?;
    
    let else_block = if let Some(else_pair) = inner.next() {
        match else_pair.as_rule() {
            Rule::block => Some(parse_block(else_pair)?),
            _ => None,
        }
    } else {
        None
    };
    
    Ok(IfStatement {
        condition,
        then_block,
        else_block,
    })
}

fn parse_for_loop(pair: Pair<Rule>) -> Result<ForLoop, String> {
    let mut inner = pair.into_inner();
    // Skip "for"
    let var_name = parse_identifier(inner.next().ok_or("Missing variable name in for loop")?)?;
    // Skip "in"
    let start_str = inner
        .find(|p| p.as_rule() == Rule::integer)
        .ok_or("Missing start value in for loop")?
        .as_str();
    let start = start_str.parse().map_err(|_| "Invalid start integer in for loop")?;
    // Skip ".."
    let end_str = inner
        .find(|p| p.as_rule() == Rule::integer)
        .ok_or("Missing end value in for loop")?
        .as_str();
    let end = end_str.parse().map_err(|_| "Invalid end integer in for loop")?;
    let body = parse_block(inner.next().ok_or("Missing body in for loop")?)?;
    
    Ok(ForLoop {
        var_name,
        start,
        end,
        body,
    })
}

fn parse_return_statement(pair: Pair<Rule>) -> Result<ReturnStatement, String> {
    let value = parse_expression(pair.into_inner().next().ok_or("Missing return value")?)?;
    Ok(ReturnStatement { value })
}

fn parse_directive(pair: Pair<Rule>) -> Result<Directive, String> {
    let inner_pair = pair.into_inner().next().ok_or("Empty directive")?;
    
    match inner_pair.as_rule() {
        Rule::print_directive => Ok(Directive::Print(parse_print_directive(inner_pair)?)),
        Rule::assert_directive => Ok(Directive::Assert(parse_assert_directive(inner_pair)?)),
        Rule::abort_directive => Ok(Directive::Abort(parse_abort_directive(inner_pair)?)),
        Rule::reveal_directive => Ok(Directive::Reveal(parse_reveal_directive(inner_pair)?)),
        Rule::debug_directive => Ok(Directive::Debug(parse_debug_directive(inner_pair)?)),
        _ => Err(format!("Unexpected directive rule: {:?}", inner_pair.as_rule())),
    }
}

fn parse_print_directive(pair: Pair<Rule>) -> Result<PrintDirective, String> {
    let mut expressions = Vec::new();
    
    if let Some(expr_list_pair) = pair.into_inner().find(|p| p.as_rule() == Rule::expression_list) {
        for expr_pair in expr_list_pair.into_inner() {
            if expr_pair.as_rule() == Rule::expression {
                expressions.push(parse_expression(expr_pair)?);
            }
        }
    }
    
    Ok(PrintDirective { expressions })
}

fn parse_assert_directive(pair: Pair<Rule>) -> Result<AssertDirective, String> {
    let mut inner = pair.into_inner();
    let condition = parse_expression(inner.next().ok_or("Missing condition in assert")?)?;
    
    let message = inner
        .find(|p| p.as_rule() == Rule::string)
        .map(|p| parse_string(p))
        .transpose()?;
    
    Ok(AssertDirective { condition, message })
}

fn parse_abort_directive(pair: Pair<Rule>) -> Result<AbortDirective, String> {
    let string_pair = pair
        .into_inner()
        .find(|p| p.as_rule() == Rule::string)
        .ok_or("Missing message in abort")?;
    let message = parse_string(string_pair)?;
    
    Ok(AbortDirective { message })
}

fn parse_reveal_directive(pair: Pair<Rule>) -> Result<RevealDirective, String> {
    let identifier = parse_identifier(pair.into_inner().next().ok_or("Missing identifier in reveal")?)?;
    Ok(RevealDirective { identifier })
}

fn parse_debug_directive(pair: Pair<Rule>) -> Result<DebugDirective, String> {
    let block = parse_block(pair.into_inner().next().ok_or("Missing block in debug")?)?;
    Ok(DebugDirective { block })
}

fn parse_expression(pair: Pair<Rule>) -> Result<Expression, String> {
    match pair.as_rule() {
        Rule::expression => parse_expression(pair.into_inner().next().ok_or("Empty expression")?),
        Rule::logical_or => parse_logical_or(pair),
        Rule::logical_and => parse_logical_and(pair),
        Rule::comparison => parse_comparison(pair),
        Rule::bitwise_or => parse_bitwise_or(pair),
        Rule::bitwise_xor => parse_bitwise_xor(pair),
        Rule::bitwise_and => parse_bitwise_and(pair),
        Rule::shift => parse_shift(pair),
        Rule::additive => parse_additive(pair),
        Rule::multiplicative => parse_multiplicative(pair),
        Rule::unary => parse_unary(pair),
        Rule::postfix => parse_postfix(pair),
        Rule::primary => parse_primary(pair),
        _ => Err(format!("Unexpected expression rule: {:?}", pair.as_rule())),
    }
}

fn parse_logical_or(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    if inner.is_empty() {
        return Err("Empty logical_or expression".to_string());
    }
    
    let mut left = parse_expression(inner.remove(0))?;
    
    // Handle repetition: (logical_and ~ ("||" ~ logical_and)*)
    // Pest will give us pairs in order: first logical_and, then each logical_and from repetition
    // The "||" literal is part of the match but not a separate pair
    for right_pair in inner {
        let right = parse_expression(right_pair)?;
        left = Expression {
            base: ExpressionBase::BinaryOp(BinaryOp::LogicalOr(Box::new(left), Box::new(right))),
            accesses: Vec::new(),
        };
    }
    
    Ok(left)
}

fn parse_logical_and(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    if inner.is_empty() {
        return Err("Empty logical_and expression".to_string());
    }
    
    let mut left = parse_expression(inner.remove(0))?;
    
    // Handle repetition: (comparison ~ ("&&" ~ comparison)*)
    for right_pair in inner {
        let right = parse_expression(right_pair)?;
        left = Expression {
            base: ExpressionBase::BinaryOp(BinaryOp::LogicalAnd(Box::new(left), Box::new(right))),
            accesses: Vec::new(),
        };
    }
    
    Ok(left)
}

fn parse_comparison(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner = pair.into_inner();
    let left = parse_expression(inner.next().ok_or("Missing left operand in comparison")?)?;
    
    if let Some(op_pair) = inner.next() {
        let op = match op_pair.as_str() {
            "==" => ComparisonOp::Equal,
            "!=" => ComparisonOp::NotEqual,
            "<=" => ComparisonOp::LessThanOrEqual,
            ">=" => ComparisonOp::GreaterThanOrEqual,
            "<" => ComparisonOp::LessThan,
            ">" => ComparisonOp::GreaterThan,
            _ => return Err(format!("Invalid comparison operator: {}", op_pair.as_str())),
        };
        let right = parse_expression(inner.next().ok_or("Missing right operand in comparison")?)?;
        Ok(Expression {
            base: ExpressionBase::BinaryOp(BinaryOp::Comparison(op, Box::new(left), Box::new(right))),
            accesses: Vec::new(),
        })
    } else {
        Ok(left)
    }
}

fn parse_bitwise_or(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    if inner.is_empty() {
        return Err("Empty bitwise_or expression".to_string());
    }
    
    let mut left = parse_expression(inner.remove(0))?;
    
    // Handle repetition: (bitwise_xor ~ ("|" ~ bitwise_xor)*)
    for right_pair in inner {
        let right = parse_expression(right_pair)?;
        left = Expression {
            base: ExpressionBase::BinaryOp(BinaryOp::BitwiseOr(Box::new(left), Box::new(right))),
            accesses: Vec::new(),
        };
    }
    
    Ok(left)
}

fn parse_bitwise_xor(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    if inner.is_empty() {
        return Err("Empty bitwise_xor expression".to_string());
    }
    
    let mut left = parse_expression(inner.remove(0))?;
    
    // Handle repetition: (bitwise_and ~ ("^" ~ bitwise_and)*)
    for right_pair in inner {
        let right = parse_expression(right_pair)?;
        left = Expression {
            base: ExpressionBase::BinaryOp(BinaryOp::BitwiseXor(Box::new(left), Box::new(right))),
            accesses: Vec::new(),
        };
    }
    
    Ok(left)
}

fn parse_bitwise_and(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    if inner.is_empty() {
        return Err("Empty bitwise_and expression".to_string());
    }
    
    let mut left = parse_expression(inner.remove(0))?;
    
    // Handle repetition: (shift ~ ("&" ~ shift)*)
    for right_pair in inner {
        let right = parse_expression(right_pair)?;
        left = Expression {
            base: ExpressionBase::BinaryOp(BinaryOp::BitwiseAnd(Box::new(left), Box::new(right))),
            accesses: Vec::new(),
        };
    }
    
    Ok(left)
}

fn parse_shift(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    if inner.is_empty() {
        return Err("Empty shift expression".to_string());
    }
    
    let mut left = parse_expression(inner.remove(0))?;
    
    // Handle repetition: (additive ~ (shift_op ~ additive)*)
    // Pest gives us: first additive, then pairs of (shift_op, additive)
    let mut i = 0;
    while i < inner.len() {
        if let Some(op_pair) = inner.get(i) {
            if op_pair.as_rule() == Rule::shift_op {
                let op = match op_pair.as_str() {
                    "<<" => ShiftOp::Left,
                    ">>" => ShiftOp::Right,
                    _ => return Err(format!("Invalid shift operator: {}", op_pair.as_str())),
                };
                i += 1;
                if i < inner.len() {
                    let right = parse_expression(inner[i].clone())?;
                    left = Expression {
                        base: ExpressionBase::BinaryOp(BinaryOp::Shift(op, Box::new(left), Box::new(right))),
                        accesses: Vec::new(),
                    };
                    i += 1;
                } else {
                    return Err("Missing right operand after shift operator".to_string());
                }
            } else {
                // This is an additive expression (right operand)
                let right = parse_expression(op_pair.clone())?;
                left = Expression {
                    base: ExpressionBase::BinaryOp(BinaryOp::Shift(ShiftOp::Left, Box::new(left), Box::new(right))),
                    accesses: Vec::new(),
                };
                i += 1;
            }
        }
    }
    
    Ok(left)
}

fn parse_additive(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    if inner.is_empty() {
        return Err("Empty additive expression".to_string());
    }
    
    let mut left = parse_expression(inner.remove(0))?;
    
    // Handle repetition: (multiplicative ~ (additive_op ~ multiplicative)*)
    // Pest gives us: first multiplicative, then pairs of (additive_op, multiplicative)
    let mut i = 0;
    while i < inner.len() {
        if let Some(op_pair) = inner.get(i) {
            if op_pair.as_rule() == Rule::additive_op {
                let op_str = op_pair.as_str();
                i += 1;
                if i < inner.len() {
                    let right = parse_expression(inner[i].clone())?;
                    left = Expression {
                        base: ExpressionBase::BinaryOp(match op_str {
                            "+" => BinaryOp::Add(Box::new(left), Box::new(right)),
                            "-" => BinaryOp::Subtract(Box::new(left), Box::new(right)),
                            _ => return Err(format!("Invalid additive operator: {}", op_str)),
                        }),
                        accesses: Vec::new(),
                    };
                    i += 1;
                } else {
                    return Err("Missing right operand after additive operator".to_string());
                }
            } else {
                // This is a multiplicative expression (right operand)
                let right = parse_expression(op_pair.clone())?;
                left = Expression {
                    base: ExpressionBase::BinaryOp(BinaryOp::Add(Box::new(left), Box::new(right))),
                    accesses: Vec::new(),
                };
                i += 1;
            }
        }
    }
    
    Ok(left)
}

fn parse_multiplicative(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    if inner.is_empty() {
        return Err("Empty multiplicative expression".to_string());
    }
    
    let mut left = parse_expression(inner.remove(0))?;
    
    // Handle repetition: (unary ~ (multiplicative_op ~ unary)*)
    // Pest gives us: first unary, then pairs of (multiplicative_op, unary)
    let mut i = 0;
    while i < inner.len() {
        if let Some(op_pair) = inner.get(i) {
            if op_pair.as_rule() == Rule::multiplicative_op {
                let op_str = op_pair.as_str();
                i += 1;
                if i < inner.len() {
                    let right = parse_expression(inner[i].clone())?;
                    left = Expression {
                        base: ExpressionBase::BinaryOp(match op_str {
                            "*" => BinaryOp::Multiply(Box::new(left), Box::new(right)),
                            "/" => BinaryOp::Divide(Box::new(left), Box::new(right)),
                            "%" => BinaryOp::Modulo(Box::new(left), Box::new(right)),
                            _ => return Err(format!("Invalid multiplicative operator: {}", op_str)),
                        }),
                        accesses: Vec::new(),
                    };
                    i += 1;
                } else {
                    return Err("Missing right operand after multiplicative operator".to_string());
                }
            } else {
                // This is a unary expression (right operand)
                let right = parse_expression(op_pair.clone())?;
                left = Expression {
                    base: ExpressionBase::BinaryOp(BinaryOp::Multiply(Box::new(left), Box::new(right))),
                    accesses: Vec::new(),
                };
                i += 1;
            }
        }
    }
    
    Ok(left)
}

fn parse_unary(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner: Vec<_> = pair.into_inner().collect();
    let mut unary_ops = Vec::new();
    let mut postfix_idx = 0;
    
    // Collect unary operators
    for (i, p) in inner.iter().enumerate() {
        match p.as_rule() {
            Rule::unary_op => {
                unary_ops.push(p.as_str());
            }
            Rule::postfix => {
                postfix_idx = i;
                break;
            }
            _ => {}
        }
    }
    
    let postfix_pair = inner.get(postfix_idx).ok_or("Missing postfix expression in unary")?;
    let mut expr = parse_postfix(postfix_pair.clone())?;
    
    // Apply unary operators in reverse order (right to left)
    for op in unary_ops.iter().rev() {
        expr = Expression {
            base: ExpressionBase::UnaryOp(match *op {
                "-" => UnaryOp::Negate(Box::new(expr)),
                "!" => UnaryOp::Not(Box::new(expr)),
                "~" => UnaryOp::BitwiseNot(Box::new(expr)),
                _ => return Err(format!("Invalid unary operator: {}", op)),
            }),
            accesses: Vec::new(),
        };
    }
    
    Ok(expr)
}

fn parse_postfix(pair: Pair<Rule>) -> Result<Expression, String> {
    let mut inner = pair.into_inner();
    let primary_pair = inner.next().ok_or("Missing primary in postfix")?;
    let mut expr = parse_primary(primary_pair)?;
    
    // Collect postfix accesses
    let mut accesses = Vec::new();
    for access_pair in inner {
        match access_pair.as_rule() {
            Rule::array_access => {
                let index_expr = parse_expression(access_pair.into_inner().next().ok_or("Missing expression in array access")?)?;
                accesses.push(ExprAccess::Array(Box::new(index_expr)));
            }
            Rule::field_access => {
                let field_name = parse_identifier(access_pair.into_inner().next().ok_or("Missing field name")?)?;
                accesses.push(ExprAccess::Field(field_name));
            }
            _ => {}
        }
    }
    
    expr.accesses.extend(accesses);
    Ok(expr)
}

fn parse_primary(pair: Pair<Rule>) -> Result<Expression, String> {
    let inner_pair = pair.into_inner().next().ok_or("Empty primary")?;
    
    let base = match inner_pair.as_rule() {
        Rule::literal => ExpressionBase::Literal(parse_literal(inner_pair)?),
        Rule::array_literal => ExpressionBase::ArrayLiteral(parse_array_literal(inner_pair)?),
        Rule::struct_literal => ExpressionBase::StructLiteral(parse_struct_literal(inner_pair)?),
        Rule::function_call => ExpressionBase::FunctionCall(parse_function_call(inner_pair)?),
        Rule::identifier => ExpressionBase::Identifier(parse_identifier(inner_pair)?),
        Rule::expression => {
            let expr = parse_expression(inner_pair)?;
            return Ok(Expression {
                base: ExpressionBase::Parenthesized(Box::new(expr)),
                accesses: Vec::new(),
            });
        }
        _ => return Err(format!("Unexpected primary rule: {:?}", inner_pair.as_rule())),
    };
    
    Ok(Expression {
        base,
        accesses: Vec::new(),
    })
}

fn parse_literal(pair: Pair<Rule>) -> Result<Literal, String> {
    let inner_pair = pair.into_inner().next().ok_or("Empty literal")?;
    
    match inner_pair.as_rule() {
        Rule::integer => {
            let value = inner_pair.as_str().parse().map_err(|_| "Invalid integer literal")?;
            Ok(Literal::Integer(value))
        }
        Rule::bool_literal => {
            let value = match inner_pair.as_str() {
                "true" => true,
                "false" => false,
                _ => return Err(format!("Invalid bool literal: {}", inner_pair.as_str())),
            };
            Ok(Literal::Bool(value))
        }
        _ => Err(format!("Unexpected literal rule: {:?}", inner_pair.as_rule())),
    }
}

fn parse_array_literal(pair: Pair<Rule>) -> Result<ArrayLiteral, String> {
    let mut elements = Vec::new();
    
    for expr_pair in pair.into_inner() {
        if expr_pair.as_rule() == Rule::expression {
            elements.push(parse_expression(expr_pair)?);
        }
    }
    
    Ok(ArrayLiteral { elements })
}

fn parse_struct_literal(pair: Pair<Rule>) -> Result<StructLiteral, String> {
    let mut inner = pair.into_inner();
    let struct_name = parse_identifier(inner.next().ok_or("Missing struct name in struct literal")?)?;
    
    let mut fields = Vec::new();
    if let Some(field_list_pair) = inner.find(|p| p.as_rule() == Rule::field_init_list) {
        for field_pair in field_list_pair.into_inner() {
            if field_pair.as_rule() == Rule::field_init {
                fields.push(parse_field_init(field_pair)?);
            }
        }
    }
    
    Ok(StructLiteral {
        struct_name,
        fields,
    })
}

fn parse_field_init(pair: Pair<Rule>) -> Result<FieldInit, String> {
    let mut inner = pair.into_inner();
    let name = parse_identifier(inner.next().ok_or("Missing field name in field init")?)?;
    let value = parse_expression(inner.next().ok_or("Missing field value in field init")?)?;
    
    Ok(FieldInit { name, value })
}

fn parse_function_call(pair: Pair<Rule>) -> Result<FunctionCall, String> {
    let mut inner = pair.into_inner();
    let name = parse_identifier(inner.next().ok_or("Missing function name")?)?;
    
    let mut arguments = Vec::new();
    if let Some(arg_list_pair) = inner.find(|p| p.as_rule() == Rule::argument_list) {
        for expr_pair in arg_list_pair.into_inner() {
            if expr_pair.as_rule() == Rule::expression {
                arguments.push(parse_expression(expr_pair)?);
            }
        }
    }
    
    Ok(FunctionCall { name, arguments })
}

fn parse_identifier(pair: Pair<Rule>) -> Result<String, String> {
    Ok(pair.as_str().to_string())
}

fn parse_string(pair: Pair<Rule>) -> Result<String, String> {
    // Remove surrounding quotes
    let s = pair.as_str();
    if s.starts_with('"') && s.ends_with('"') {
        Ok(s[1..s.len() - 1].to_string())
    } else {
        Ok(s.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_simple_function() {
        let source = "fn add(Public Field<64> a, Public Field<64> b) -> Field<64> { return a + b; }";
        let result = parse_program(source);
        assert!(result.is_ok());
    }

    #[test]
    fn test_parse_struct() {
        let source = "struct Point { Field<64> x; Field<64> y; }";
        let result = parse_program(source);
        assert!(result.is_ok());
    }

    #[test]
    fn test_parse_variable_decl() {
        let source = "fn test() -> Field<64> { let Public Field<64> x = 5; return x; }";
        let result = parse_program(source);
        assert!(result.is_ok());
    }

    #[test]
    fn test_parse_if_statement() {
        let source = "fn test(Public Field<64> a) -> Field<64> { if a > 0 { return a; } else { return 0; } }";
        let result = parse_program(source);
        assert!(result.is_ok());
    }

    #[test]
    fn test_parse_binary_operations() {
        let source = "fn test(Public Field<64> a, Public Field<64> b) -> Field<64> { return a + b * 2; }";
        let result = parse_program(source);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_ast_simple_function() {
        let source = "fn add(Public Field<64> a, Public Field<64> b) -> Field<64> { return a + b; }";
        let pairs = parse_program(source).unwrap();
        let result = build_ast(pairs);
        assert!(result.is_ok());
        
        let program = result.unwrap();
        assert_eq!(program.items.len(), 1);
        
        if let Item::FunctionDef(func) = &program.items[0] {
            assert_eq!(func.name, "add");
            assert_eq!(func.params.len(), 2);
            assert_eq!(func.params[0].name, "a");
            assert_eq!(func.params[1].name, "b");
        } else {
            panic!("Expected function definition");
        }
    }

    #[test]
    fn test_build_ast_struct() {
        let source = "struct Point { Field<64> x; Field<64> y; }";
        let pairs = parse_program(source).unwrap();
        let result = build_ast(pairs);
        assert!(result.is_ok());
        
        let program = result.unwrap();
        if let Item::StructDef(struct_def) = &program.items[0] {
            assert_eq!(struct_def.name, "Point");
            assert_eq!(struct_def.fields.len(), 2);
        } else {
            panic!("Expected struct definition");
        }
    }
}

