//! SNP Private Set Intersection benchmark — Yao garbled circuits.
//!
//! Two parties each hold 64 heterozygous SNP rsid integers from a 23andMe-
//! style genotype file.  The garbled circuit computes the intersection size
//! without revealing which rsids either party carries.
//!
//! The intersection size / 64 is a rough kinship coefficient:
//!   ~50% → first-degree relative (parent-child, full sibling)
//!   ~25% → second-degree relative (grandparent, half-sibling)
//!   ~12% → third-degree relative (first cousin)
//!   ~0%  → unrelated
//!
//! Input TOML is generated by tests/samples/snp_prep.py from real SNP data.
//! The combined TOML contains Alice's 64 rsids then Bob's 64 rsids (128
//! total), which the circuit consumes in that order.
//!
//! RSid integers fit in 30 bits so 32-bit Yao arithmetic is exact — no
//! 63-bit Mersenne prime overhead needed.
//!
//! Run: cargo bench -p bench --bench snp_psi

use std::{path::Path, time::{Duration, Instant}};

use criterion::{criterion_group, criterion_main, Criterion};
use garbledc::{backend::YaoBackend, ot::{OTReceiver, OTSender}};
use ir::lir::{Program, WireId};
use net::{stub_networks, NetworkLayer};
use runtime::{
    compile_to_vm_instructions,
    vm::{Backend, VMState},
};
use serde::{Deserialize, Serialize};

// ─── 32-bit Yao is sufficient: rsids ≤ 30 bits, count ≤ 7 bits ──────────────
const YAO_BITS: usize = 32;

// ─── Helpers (shared with mnist bench) ───────────────────────────────────────

#[derive(Deserialize)]
struct InputsToml {
    inputs: InputsSection,
}
#[derive(Deserialize)]
struct InputsSection {
    values: Vec<u64>,
}

fn load_values(toml_path: &str) -> Vec<u64> {
    let text = std::fs::read_to_string(toml_path)
        .unwrap_or_else(|_| panic!("cannot read {toml_path}; run tests/samples/snp_prep.py first"));
    toml::from_str::<InputsToml>(&text)
        .unwrap_or_else(|e| panic!("TOML parse error in {toml_path}: {e}"))
        .inputs
        .values
}

fn load_circuit(ir_path: &str) -> Program {
    let bytes = std::fs::read(ir_path)
        .unwrap_or_else(|_| panic!("cannot read {ir_path}; compile with `helixc compile`"));
    Program::from_bytes(&bytes)
        .unwrap_or_else(|e| panic!("circuit deserialize: {e}"))
}

fn n_wires(prog: &Program) -> usize {
    prog.circuit
        .gates
        .iter()
        .map(|g| g.output.0 as usize)
        .chain(prog.circuit.inputs.iter().map(|i| i.wire.0 as usize))
        .max()
        .unwrap_or(0)
        + 1
}

fn field_mod(prog: &Program) -> u64 {
    const M63: u64 = (1u64 << 63) - 1;
    prog.metadata.field_modulus.unwrap_or(M63)
}

// ─── Yao single-process ───────────────────────────────────────────────────────

fn yao_single(prog: &Program, vals: &[u64]) -> Vec<(WireId, u64)> {
    let mut backend = YaoBackend::new(YAO_BITS);
    let instructions = compile_to_vm_instructions(&prog.circuit);
    let mut state = VMState::new(n_wires(prog), field_mod(prog));
    for instr in &instructions {
        backend.execute_instruction(instr, &mut state).unwrap();
    }
    for (inp, &v) in prog.circuit.inputs.iter().zip(vals.iter()) {
        backend
            .set_input(inp.wire, v, runtime::Visibility::Secret, &mut state)
            .unwrap();
    }
    let (gc, active_labels, decode) = backend.finalize_garbler();
    let final_labels = gc.evaluate(active_labels);
    prog.circuit
        .outputs
        .iter()
        .map(|&w| {
            let base = backend.wire_base_slot(w);
            let mut val = 0u64;
            for b in 0..YAO_BITS {
                if let Some(lbl) = final_labels.get(base + b).and_then(|x| *x) {
                    val |= (((lbl & 1) ^ decode[base + b] as u128) as u64) << b;
                }
            }
            (w, val)
        })
        .collect()
}

// ─── Yao 2P networked ────────────────────────────────────────────────────────

async fn net_send<T: Serialize>(n: &mut impl NetworkLayer, to: usize, v: &T) {
    n.send_to(to, bincode::serialize(v).unwrap()).await.unwrap();
}
async fn net_recv<T: for<'de> Deserialize<'de>>(n: &mut impl NetworkLayer, from: usize) -> T {
    bincode::deserialize(&n.recv_from(from).await.unwrap()).unwrap()
}

#[derive(Serialize, Deserialize)]
struct GarblerBundle {
    gc:                garbledc::circuit::Circuit,
    active:            Vec<Option<u128>>,
    decode:            Vec<u8>,
    ot:                Vec<(u128, u128)>,
    eval_base_slots:   Vec<usize>,
    output_base_slots: Vec<usize>,
}

async fn garbler(
    prog: Program,
    vals: Vec<(WireId, u64)>,
    eval_wires: Vec<WireId>,
    mut net: impl NetworkLayer,
) {
    let mut backend = YaoBackend::new(YAO_BITS);
    let instructions = compile_to_vm_instructions(&prog.circuit);
    let mut state = VMState::new(n_wires(&prog), field_mod(&prog));
    for instr in &instructions {
        backend.execute_instruction(instr, &mut state).unwrap();
    }
    for &(w, v) in &vals {
        backend
            .set_input(w, v, runtime::Visibility::Secret, &mut state)
            .unwrap();
    }
    let mut ot_msgs: Vec<(u128, u128)> = Vec::new();
    let mut eval_base_slots: Vec<usize> = Vec::new();
    for &w in &eval_wires {
        backend.register_evaluator_wire(w);
        eval_base_slots.push(backend.wire_base_slot(w));
        for b in 0..YAO_BITS {
            let [l0, l1] = backend.wire_label_pair(w, b).unwrap();
            ot_msgs.push((l0, l1));
        }
    }
    let output_base_slots: Vec<usize> = prog.circuit.outputs.iter()
        .map(|&w| backend.wire_base_slot(w))
        .collect();
    let (ot_sender, a) = OTSender::setup(ot_msgs.len());
    net_send(&mut net, 1, &a).await;
    let b_bytes: Vec<[u8; 32]> = net_recv(&mut net, 1).await;
    let ot = ot_sender.respond(&b_bytes, &ot_msgs);
    let (gc, active, decode) = backend.finalize_garbler();
    net_send(&mut net, 1, &GarblerBundle { gc, active, decode, ot, eval_base_slots, output_base_slots }).await;
    let _: Vec<u64> = net_recv(&mut net, 1).await;
}

async fn evaluator(
    _prog: Program,
    vals: Vec<(WireId, u64)>,
    mut net: impl NetworkLayer,
) {
    let choices: Vec<bool> = vals
        .iter()
        .flat_map(|&(_, v)| (0..YAO_BITS).map(move |i| (v >> i) & 1 == 1))
        .collect();
    let a: Vec<[u8; 32]> = net_recv(&mut net, 0).await;
    let (ot_recv, b) = OTReceiver::choose(&a, &choices);
    net_send(&mut net, 0, &b).await;
    let bundle: GarblerBundle = net_recv(&mut net, 0).await;
    let my_labels = ot_recv.finish(&bundle.ot);
    let mut active = bundle.active;
    for (i, &base) in bundle.eval_base_slots.iter().enumerate() {
        for b in 0..YAO_BITS {
            active[base + b] = Some(my_labels[i * YAO_BITS + b]);
        }
    }
    let final_labels = bundle.gc.evaluate(active);
    let outputs: Vec<u64> = bundle.output_base_slots.iter()
        .map(|&base| {
            let mut val = 0u64;
            for b in 0..YAO_BITS {
                if let Some(lbl) = final_labels.get(base + b).and_then(|x| *x) {
                    val |= (((lbl & 1) ^ bundle.decode[base + b] as u128) as u64) << b;
                }
            }
            val
        })
        .collect();
    net_send(&mut net, 0, &outputs).await;
}

async fn yao_2p_run(prog: &Program, vals: &[u64]) {
    let all: Vec<(WireId, u64)> = prog
        .circuit
        .inputs
        .iter()
        .zip(vals.iter())
        .map(|(i, &v)| (i.wire, v))
        .collect();
    // First 64 inputs belong to Alice (garbler), last 64 to Bob (evaluator).
    let n = all.len() / 2;
    let garbler_vals: Vec<_> = all[..n].to_vec();
    let eval_vals:    Vec<_> = all[n..].to_vec();
    let eval_wires:   Vec<_> = eval_vals.iter().map(|&(w, _)| w).collect();

    let mut stubs = stub_networks(2);
    let s0 = stubs.remove(0);
    let s1 = stubs.remove(0);
    let p0 = prog.clone();
    let p1 = prog.clone();
    tokio::try_join!(
        tokio::spawn(async move { garbler(p0, garbler_vals, eval_wires, s0).await }),
        tokio::spawn(async move { evaluator(p1, eval_vals, s1).await }),
    )
    .unwrap();
}

// ─── Criterion group ──────────────────────────────────────────────────────────

fn bench_snp_psi(c: &mut Criterion) {
    let rt   = tokio::runtime::Runtime::new().unwrap();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();

    let prog = load_circuit(
        &root.join("tests/samples/snp_psi.ir").to_string_lossy()
    );
    let vals = load_values(
        &root.join("tests/samples/snp_psi_combined.toml").to_string_lossy()
    );

    // ── Correctness pre-check ─────────────────────────────────────────────────
    // Intersection should be 32/64 (simulated first-degree relative).
    let outputs = yao_single(&prog, &vals);
    let intersection = outputs.first().map(|&(_, v)| v).unwrap_or(0);
    eprintln!(
        "\nSNP PSI correctness check ({YAO_BITS}-bit Yao)... \
         intersection = {intersection}/64  \
         ({:.0}% kinship — {})",
        100.0 * intersection as f64 / 64.0,
        match intersection {
            i if i >= 24 => "first-degree relative",
            i if i >= 12 => "second-degree relative",
            i if i >=  6 => "third-degree relative",
            _             => "unrelated",
        }
    );
    assert_eq!(
        intersection, 32,
        "expected intersection=32 for simulated sibling, got {intersection}"
    );

    let mut group = c.benchmark_group("snp_psi_64");
    group.sample_size(10);
    group.measurement_time(Duration::from_secs(3600));

    // ── Single-process (garbler + evaluator in one process) ───────────────────
    group.bench_function("single_process", |b| {
        b.iter_custom(|iters| {
            let mut total = Duration::ZERO;
            for _ in 0..iters {
                let start = Instant::now();
                yao_single(&prog, &vals);
                total += start.elapsed();
            }
            total
        });
    });

    // ── Networked 2-party (Alice garbles, Bob evaluates, OT over channels) ────
    group.bench_function("networked_2p", |b| {
        b.to_async(&rt).iter(|| yao_2p_run(&prog, &vals));
    });

    group.finish();
}

criterion_group!(benches, bench_snp_psi);
criterion_main!(benches);
