#!/usr/bin/env python3
"""
MNIST test-image preprocessing — generate bench/data/mnist_images.toml.

Reads the standard MNIST IDX files (t10k-images.gz, t10k-labels.gz) from the
same directory as this script.  For each digit class 0–9 it picks the first
test image with that label, encodes pixels with the same fixed-point scale used
during training (field_value = pixel_u8 * 64 // 255), and writes a TOML file
that the Rust benchmark loads at runtime.

Pixel encoding matches the dacorvo/mnist-mlp training script:
  scale = 64  →  pixel_field = int(pixel_u8) * 64 // 255

Usage:
  cd bench/data && python3 mnist_prep.py

If the .gz files are missing they are downloaded automatically from the
PyTorch S3 mirror (ossci-datasets.s3.amazonaws.com/mnist/).
"""

import gzip
import os
import struct
import urllib.request

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

IMAGES_GZ = os.path.join(SCRIPT_DIR, "t10k-images.gz")
LABELS_GZ  = os.path.join(SCRIPT_DIR, "t10k-labels.gz")
OUTPUT     = os.path.join(SCRIPT_DIR, "mnist_images.toml")

MIRROR = "https://ossci-datasets.s3.amazonaws.com/mnist/"
REMOTE = {
    "t10k-images.gz": "t10k-images-idx3-ubyte.gz",
    "t10k-labels.gz": "t10k-labels-idx1-ubyte.gz",
}

SCALE = 64  # fixed-point scale used during training

# ── Download if needed ────────────────────────────────────────────────────────

for local_name, remote_name in REMOTE.items():
    local_path = os.path.join(SCRIPT_DIR, local_name)
    if not os.path.exists(local_path):
        url = MIRROR + remote_name
        print(f"Downloading {url} …")
        urllib.request.urlretrieve(url, local_path)
        print(f"  saved to {local_path}")

# ── Parse IDX files ───────────────────────────────────────────────────────────

def read_images(path):
    with gzip.open(path, "rb") as f:
        magic, n, rows, cols = struct.unpack(">4I", f.read(16))
    assert magic == 0x00000803, f"unexpected magic {magic:#010x} in {path}"
    with gzip.open(path, "rb") as f:
        f.read(16)
        data = f.read()
    assert len(data) == n * rows * cols
    return data, n, rows, cols

def read_labels(path):
    with gzip.open(path, "rb") as f:
        magic, n = struct.unpack(">2I", f.read(8))
    assert magic == 0x00000801, f"unexpected magic {magic:#010x} in {path}"
    with gzip.open(path, "rb") as f:
        f.read(8)
        data = f.read()
    assert len(data) == n
    return list(data), n

image_data, n_images, rows, cols = read_images(IMAGES_GZ)
labels, n_labels = read_labels(LABELS_GZ)
assert n_images == n_labels, "image/label count mismatch"
assert rows == 28 and cols == 28, f"expected 28×28, got {rows}×{cols}"

print(f"Loaded {n_images} test images ({rows}×{cols})")

# ── Pick first occurrence of each digit ───────────────────────────────────────

pixels_per_image = rows * cols  # 784
selected = {}  # digit → (test_index, pixel_list)

for idx in range(n_images):
    digit = labels[idx]
    if digit in selected:
        continue
    start = idx * pixels_per_image
    raw   = image_data[start : start + pixels_per_image]
    encoded = [int(px) * SCALE // 255 for px in raw]
    selected[digit] = (idx, encoded)
    if len(selected) == 10:
        break

assert len(selected) == 10, "could not find all 10 digit classes in test set"

ordered_labels = [selected[d][0] for d in range(10)]   # source test indices
ordered_pixels = [selected[d][1] for d in range(10)]   # encoded pixel lists

print("Selected test indices (one per digit 0–9):", [selected[d][0] for d in range(10)])

# ── Write TOML ────────────────────────────────────────────────────────────────

def fmt_row(values, indent=2, width=16):
    """Format a list of ints as a wrapped TOML inline sequence."""
    lines = []
    row = []
    for v in values:
        row.append(str(v))
        if len(row) == width:
            lines.append(" " * indent + ", ".join(row) + ",")
            row = []
    if row:
        lines.append(" " * indent + ", ".join(row) + ",")
    return "\n".join(lines)

with open(OUTPUT, "w") as f:
    f.write("# Generated by bench/data/mnist_prep.py — do not edit by hand.\n")
    f.write(f"# pixel encoding: field_value = pixel_u8 * {SCALE} // 255\n")
    f.write("# 10 images × 784 pixels each; image i corresponds to digit i.\n")
    f.write("\n")
    f.write("[labels]\n")
    f.write("values = [" + ", ".join(str(d) for d in range(10)) + "]\n")
    f.write("\n")
    f.write("[source_indices]\n")
    src = [selected[d][0] for d in range(10)]
    f.write("values = [" + ", ".join(str(i) for i in src) + "]\n")
    f.write("\n")
    f.write("[pixels]\n")
    f.write("# 10 × 784 = 7840 values; image 0 first, then image 1, etc.\n")
    f.write("values = [\n")
    for d in range(10):
        f.write(f"  # digit {d} (MNIST test index {selected[d][0]})\n")
        flat = ordered_pixels[d]
        for i in range(0, len(flat), 28):
            row = flat[i:i+28]
            sep = "," if (i + 28 < len(flat) or d < 9) else ""
            f.write("  " + ", ".join(str(v) for v in row) + sep + "\n")
    f.write("]\n")

print(f"Wrote {OUTPUT}")
print(f"  labels:        {list(range(10))}")
print(f"  source_indices: {src}")
